[tools]
gcloud = "552"
"github:Cyclenerd/google-cloud-pricing-cost-calculator" = "latest"
go = "1.25"
terraform = "1.14"
typst = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true

[task_config]
# NOTE: scripts defined in `scripts/` are used for production
includes = [
    "scripts"
]

# NOTE: Tasks defined in this file serve only the development needs

[tasks.valkey-docker]
description = "Run valkey docker image. This is used only for development"
run = '''
#!/usr/bin/env bash
# Calculate the cores to use, equivalent to min(nproc/4, 8)
NUM_CORES=$(nproc)
IDLE_CORES=$((NUM_CORES / 4))
if [ "$IDLE_CORES" -gt 8 ]; then
  IDLE_CORES=8
fi
IO_THREADS=$((NUM_CORES - IDLE_CORES))

docker run --rm -p 6379:6379 valkey/valkey:9.0.1 \
    --io-threads "$IO_THREADS"
'''

[tasks.build]
description = "Build binaries for benchmark"
run = "docker build -f Dockerfile.build -t valkey-builder --output ./bin ."

[tasks.redeploy]
description = "Deploy the benchmark on GCP"
depends = ["build"]
run = '''
#!/usr/bin/env bash
cd terraform 
terraform init
terraform destroy --auto-approve 
terraform apply --auto-approve
'''

[tasks.destroy]
description = "Destory the deployed infrastructure"
run = "cd terraform && terraform destroy --auto-approve"

[tasks.destroy-sut]
description = "Destory the deployed SUT nodes"
run = '''
cd ./terraform
terraform destroy \
    -target="google_compute_instance.sut_nodes" \
    --auto-approve
'''

[tasks.monitor]
description = "Enter monitoring of the client node"
run = "gcloud compute ssh valkey-client-node --zone=us-west1-c --ssh-flag='-t' --command='btop'"
